FROM node:lts-slim
ARG STRAPI_URL
ARG DATABASE_PORT
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG ADMIN_JWT_SECRET

WORKDIR /app
COPY ./strapi/package.json ./
COPY ./strapi/yarn.lock ./

RUN yarn

COPY ./strapi .

ENV STRAPI_URL=$STRAPI_URL
ENV DATABASE_PORT=$DATABASE_PORT
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_USERNAME=$DATABASE_USERNAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET
ENV NODE_ENV=production

RUN yarn run build --clean

EXPOSE 1337

CMD ["yarn", "run", "start"]
