api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /middlewares.yml

certificatesResolvers:
  http:
    acme:
      email: contact@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: http

accessLog: {}
